name: root
channels:
  - pytorch
  - conda-forge
dependencies:
  - scipy
  - numpy
  - pandas
  - jupyter
  - matplotlib
  - scikit-learn
  - seaborn
  - nilearn
  - keras
  - tensorflow
  - pytorch-cpu
  - torchvision-cpu
  - lightgbm
  - xgboost
  - catboost
  - statsmodels
  - joblib
  - networkx
  - tslearn
  - pip
  - pip:
      - https://api.github.com/repos/paris-saclay-cds/ramp-workflow/zipball/master
      - https://api.github.com/repos/parisots/gcn/zipball/master
      - slidingwindow
