name: neurodevelop
channels:
  - conda-forge
dependencies:
  - scipy
  - numpy
  - pandas
  - jupyter
  - matplotlib
  - scikit-learn
  - seaborn
  - nilearn
  - cloudpickle
  - pip
  - pip:
    - https://api.github.com/repos/paris-saclay-cds/ramp-workflow/zipball/master
